
import { Language } from './types';

export const translations: Record<Language, Record<string, string>> = {
    en: {
        welcome: 'Welcome to Cultur',
        chooseLanguage: 'Choose your language',
        english: 'English',
        russian: 'Russian',
        login: 'Login',
        register: 'Register',
        nickname: 'Nickname',
        email: 'Email',
        password: 'Password',
        authPrompt: 'Please log in or register to continue.',
        dashboard: 'Dashboard',
        newsFeed: 'News Feed',
        adminPanel: 'Admin Panel',
        userManagement: 'User Management',
        contentManagement: 'Content Management',
        logout: 'Logout',
        all: 'All',
        news: 'News',
        videos: 'Videos',
        music: 'Music',
        myPlaylists: 'My Playlists',
        createPlaylist: 'Create Playlist',
        playlistName: 'Playlist Name',
        addToPlaylist: 'Add to Playlist',
        offlineNote: 'Playlists are saved on this device for offline access.',
        generateWithAI: 'Generate with AI',
        title: 'Title',
        description: 'Description',
        imageURL: 'Image URL',
        contentURL: 'Content URL',
        type: 'Type',
        publish: 'Publish',
        edit: 'Edit',
        delete: 'Delete',
        role: 'Role',
        actions: 'Actions',
        save: 'Save',
        cancel: 'Cancel',
        confirmDelete: 'Are you sure you want to delete this?',
        promoteToEditor: 'Promote to Editor',
        demoteToUser: 'Demote to User'
    },
    ru: {
        welcome: 'Добро пожаловать в Cultur',
        chooseLanguage: 'Выберите ваш язык',
        english: 'Английский',
        russian: 'Русский',
        login: 'Вход',
        register: 'Регистрация',
        nickname: 'Никнейм',
        email: 'Почта',
        password: 'Пароль',
        authPrompt: 'Пожалуйста, войдите или зарегистрируйтесь, чтобы продолжить.',
        dashboard: 'Панель управления',
        newsFeed: 'Лента новостей',
        adminPanel: 'Админ-панель',
        userManagement: 'Управление пользователями',
        contentManagement: 'Управление контентом',
        logout: 'Выйти',
        all: 'Все',
        news: 'Новости',
        videos: 'Видео',
        music: 'Музыка',
        myPlaylists: 'Мои плейлисты',
        createPlaylist: 'Создать плейлист',
        playlistName: 'Название плейлиста',
        addToPlaylist: 'Добавить в плейлист',
        offlineNote: 'Плейлисты сохраняются на этом устройстве для оффлайн доступа.',
        generateWithAI: 'Сгенерировать с ИИ',
        title: 'Заголовок',
        description: 'Описание',
        imageURL: 'URL изображения',
        contentURL: 'URL контента',
        type: 'Тип',
        publish: 'Опубликовать',
        edit: 'Редактировать',
        delete: 'Удалить',
        role: 'Роль',
        actions: 'Действия',
        save: 'Сохранить',
        cancel: 'Отмена',
        confirmDelete: 'Вы уверены, что хотите удалить это?',
        promoteToEditor: 'Назначить редактором',
        demoteToUser: 'Разжаловать до пользователя'
    }
};
